django/accounts/urls.py
from django.urls import path
from . import views


urlpatterns= [
    path('register',views.RegisterViews.as_view(),name="register"),
]

django/blog/urls.py
from django.urls import path
from .import views



app_name = "blog"
urlpatterns =[
    path('',views.BlogListViews.as_view(),name= "blog_list"),
    path('<int:pk>/',views.BlogDetailviewa.as_view(),name = "blogid"),
    path('new/',views.BlogPostViews.as_view(),name="new"),
    path('<int:pk>/edit/',views.BlogUpdateView.as_view(),name= "edit"),
    path('<int:pk>/delete/',views.BlogDeletePost.as_view(),name= "delete"),
]

django/pages/urls.py
from django.urls import path
from . import views

app_name = "asd" 
urlpatterns = [
path('',views.HomepageViews.as_view(),name="home"),
path('about/',views.AboutViews.as_view(),name ="about"),
]

django/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('',views.PostListViews.as_view(),name='post_list'),
]


django/tester/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path( 'posts/',include('posts.urls')),
    path( 'blog/',include('blog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path( '',include('pages.urls')),
]

django/accounts/models.py
from django.db import models

# Create your models here.

django/blog/models.py
from typing import List, Optional, Set
from django.db import models
from django.urls import reverse
# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=20)
    body = models.TextField()
    author = models.ForeignKey("auth.user",on_delete=models.CASCADE)


    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse("blog:blogid",args=[str(self.id)])
        # return reverse("blog:blogid",kwargs={"pk":self.id})
        
    




django/pages/models.py
from django.db import models

# Create your models here.

django/posts/models.py
from django.db import models

# Create your models here.
class post(models.Model):
    text = models.TextField()




    def __str__(self):
        return self.text[:10]


django/accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


                                       

class RegisterViews(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login") 
    template_name = "registration/register.html"

django/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Blog
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
# Create your views here.

class BlogListViews(ListView):
    model = Blog
    template_name = "blog/blog_list.html"



# 1
# def Detailviews(request,BlogId):
#     vlog = Blog.objects.get(id=BlogId)
#     context= {"Blog":vlog}
#     return render(request,"blog/detail.html",context)


# 2
class BlogDetailviewa(DetailView):
    model = Blog
    template_name = 'blog/detail.html'




class BlogPostViews(CreateView):
    model = Blog
    template_name = "blog/new.html"
    fields =['title','body','author']


class BlogUpdateView(UpdateView):
    model = Blog
    template_name = "blog/edit.html"
    fields = ['title','body']


class BlogDeletePost(DeleteView):
    model = Blog
    template_name ="blog/delete.html" 
    success_url= reverse_lazy("blog:blog_list")

django/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView

# def home(request):
#    return render(request,'pages/home.html',{})

class HomepageViews(TemplateView):
    template_name = 'pages/home.html'

class AboutViews(TemplateView):
    template_name = 'pages/about.html'


django/posts/views.py
from django.shortcuts import render
from .models import post
from django.views.generic import ListView
# Create your views here.

# 1
# def post_list(request):
#     posts = post.objects.all()
#     return render(request,"post/list.html",{"posts":posts})



# 2
class PostListViews(ListView):
    model = post
    template_name = "posts/list.html"
    context_object_name = "posts"


django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="top">
    <ul>
        <a href="{% url 'asd:home' %}">home</a>
        <a href="{% url 'asd:about' %}">about</a>
        <a href="{% url 'posts:post_list' %}">posts</a> 
        <!-- <p>home</p> -->
        
        {% if user.is_authenticated %}
        <li> <a href="{% url 'logout' %}">logout</a> </li>
        {% else %}
        <li> <a href="{% url 'login' %}">login</a>  </li>
        {% endif %}
    </ul>
</div>

{% block content %}

{% endblock %}



<div>
    <h3>footer</h3>
</div>

</body>
</html>

django/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block content %}
<h1> wellcome too my bloge kobs kobs</h1>
<hr>
<ul>
{% for blog in object_list %}
    <li>
        <a href="{{blog.get_absolute_url}}">{{blog.title}}</a>
    </li>
{% endfor %}
</ul>
{% endblock %}

django/templates/blog/delete.html
{% extends 'base.html' %}

{% block content %}
<h1>delete post</h1>
<hr>
<form action="" method="post">
 {% csrf_token %}
 <p>are you suor to delete post?</p>
 <input type="submit" value="delete">
</form>
{% endblock %}

django/templates/blog/detail.html
{% extends 'base.html' %}



{% block content %}
<h1>detail of {{object.title}}</h1>
<hr>
<p> {{object.body}}</p>
<a href="{% url 'blog:edit' object.id %}">Update</a>
<a href="{% url 'blog:delete' object.id %}">delete</a>
{% endblock %}

django/templates/blog/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit post</h1>
<hr>
<form action="" method="POST">
{{form.as_p}}
{% csrf_token %}
<input type="submit" value="update">
</form>
{%endblock%}

django/templates/blog/new.html
{% extends 'base.html' %}


{% block content %}
<h1> creat new post</h1>
<hr>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>

{%endblock%}

django/templates/pages/about.html
{% extends 'base.html' %}




{% block content %}
<h1> about us</h1>
{% endblock %}

django/templates/pages/home.html
{% extends 'base.html' %}



{% block content %}
<h1>hello world...</h1>
{% endblock %}


django/templates/posts/list.html
{% extends 'base.html' %}




{% block content %}
<!-- object_list -->
    <ul>
        {% for post in posts %}
        <li>
            {{post.text}}
        </li>
        <hr>
        {% endfor %}
    </ul>
        
    {% endblock %}

